[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "greenlet>=3.5.5",
    "pydantic-settings>=2.15.0",
    "pyjwt[crypto]>=2.13.0",
    "sqlalchemy>=2.0.52",
]
