"""rename attempt answer table

Revision ID: 2febe4a6999d
Revises: 75bfb561f257
Create Date: 2026-08-29 11:12:51.901925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2febe4a6999d'
down_revision: Union[str, Sequence[str], None] = '75bfb561f257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempt_answers',
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id')
    )
    op.create_index(op.f('ix_attempt_answers_attempt_id'), 'attempt_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_attempt_answers_question_id'), 'attempt_answers', ['question_id'], unique=False)
    op.drop_index(op.f('ix_attemptanswers_attempt_id'), table_name='attemptanswers')
    op.drop_index(op.f('ix_attemptanswers_question_id'), table_name='attemptanswers')
    op.drop_table('attemptanswers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attemptanswers',
    sa.Column('attempt_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], name=op.f('attemptanswers_attempt_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('attemptanswers_question_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('attemptanswers_pkey')),
    sa.UniqueConstraint('attempt_id', 'question_id', name=op.f('attemptanswers_attempt_id_question_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_attemptanswers_question_id'), 'attemptanswers', ['question_id'], unique=False)
    op.create_index(op.f('ix_attemptanswers_attempt_id'), 'attemptanswers', ['attempt_id'], unique=False)
    op.drop_index(op.f('ix_attempt_answers_question_id'), table_name='attempt_answers')
    op.drop_index(op.f('ix_attempt_answers_attempt_id'), table_name='attempt_answers')
    op.drop_table('attempt_answers')
    # ### end Alembic commands ###
