import { changeType, move, types } from './document'
import type { DraftQuestion, QuestionType } from './document'

type Props = { question: DraftQuestion; index: number; count: number; update: (q: DraftQuestion) => void; reorder: (to: number) => void; remove: () => void }
export default function QuestionEditor({ question: q, index, count, update, reorder, remove }: Props) {
  const id = `q-${q.key}`
  return <section className="editor-question" aria-labelledby={`${id}-heading`}>
    <div className="editor-question-header"><h2 id={`${id}-heading`}>Вопрос {index + 1}</h2><div className="editor-tools"><button type="button" aria-label={`Поднять вопрос ${index + 1}`} disabled={index === 0} onClick={() => reorder(index - 1)}>↑</button><button type="button" aria-label={`Опустить вопрос ${index + 1}`} disabled={index === count - 1} onClick={() => reorder(index + 1)}>↓</button><button type="button" className="danger-text" onClick={remove}>Удалить вопрос</button></div></div>
    <label htmlFor={`${id}-type`}>Тип ответа</label><select id={`${id}-type`} value={q.question_type} onChange={e => { const type = e.target.value as QuestionType; if (window.confirm('Сменить тип вопроса? Несовместимые поля ответа будут очищены.')) update(changeType(q, type)) }}>{Object.entries(types).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>
    <label htmlFor={`${id}-text`}>Текст вопроса</label><textarea id={`${id}-text`} rows={3} maxLength={20000} value={q.text} onChange={e => update({ ...q, text: e.target.value })} placeholder="Сформулируй вопрос" />
    {(q.question_type === 'single_choice' || q.question_type === 'multiple_choice') && <fieldset className="editor-options"><legend>Варианты ответа</legend><p className="hint">Отметь {q.question_type === 'single_choice' ? 'один правильный вариант' : 'все правильные варианты'}. Стрелки меняют порядок.</p>{q.options.map((o, oi) => <div className="editor-option" key={oi}><input type={q.question_type === 'single_choice' ? 'radio' : 'checkbox'} name={`${id}-correct`} aria-label={`Вопрос ${index + 1}, вариант ${oi + 1}: правильный`} checked={o.is_correct} onChange={e => update({ ...q, options: q.options.map((option, j) => ({ ...option, is_correct: j === oi ? e.target.checked : q.question_type === 'single_choice' ? false : option.is_correct })) })} /><textarea aria-label={`Вопрос ${index + 1}, вариант ${oi + 1}`} rows={2} maxLength={20000} value={o.text} onChange={e => update({ ...q, options: q.options.map((option, j) => j === oi ? { ...option, text: e.target.value } : option) })} /><div className="editor-tools"><button type="button" aria-label={`Поднять вариант ${oi + 1}`} disabled={oi === 0} onClick={() => update({ ...q, options: move(q.options, oi, oi - 1) })}>↑</button><button type="button" aria-label={`Опустить вариант ${oi + 1}`} disabled={oi === q.options.length - 1} onClick={() => update({ ...q, options: move(q.options, oi, oi + 1) })}>↓</button><button type="button" aria-label={`Удалить вариант ${oi + 1}`} disabled={q.options.length <= 2} onClick={() => update({ ...q, options: q.options.filter((_, j) => j !== oi) })}>×</button></div></div>)}<button type="button" className="secondary-action" disabled={q.options.length >= 100} onClick={() => update({ ...q, options: [...q.options, { text: '', is_correct: false }] })}>+ Добавить вариант</button></fieldset>}
    {q.question_type === 'text' && <><label htmlFor={`${id}-answer`}>Правильный ответ</label><textarea id={`${id}-answer`} rows={2} maxLength={20000} value={q.correct_answer} onChange={e => update({ ...q, correct_answer: e.target.value })} /><p className="hint">Регистр и лишние пробелы не учитываются. Синонимы нужно заменить одним ожидаемым ответом.</p></>}
    {(q.question_type === 'fill_blank' || q.question_type === 'matching') && <fieldset className="editor-options"><legend>{q.question_type === 'matching' ? 'Пары для сопоставления' : 'Поля ответа'}</legend>{q.blanks.map((b, bi) => <div className="editor-blank" key={bi}><label htmlFor={`${id}-prompt-${bi}`}>Подпись поля {bi + 1}</label><input id={`${id}-prompt-${bi}`} maxLength={20000} value={b.prompt} onChange={e => update({ ...q, blanks: q.blanks.map((blank, j) => j === bi ? { ...blank, prompt: e.target.value } : blank) })} />{q.question_type === 'matching' && <><label htmlFor={`${id}-choices-${bi}`}>Варианты — каждый с новой строки</label><textarea id={`${id}-choices-${bi}`} value={b.choices.join('\n')} onChange={e => update({ ...q, blanks: q.blanks.map((blank, j) => j === bi ? { ...blank, choices: e.target.value.split('\n') } : blank) })} /></>}<label htmlFor={`${id}-blank-${bi}`}>Правильный ответ</label>{q.question_type === 'matching' ? <select id={`${id}-blank-${bi}`} value={b.choices.map(c => c.trim()).includes(b.correct_answer) ? b.correct_answer : ''} onChange={e => update({ ...q, blanks: q.blanks.map((blank, j) => j === bi ? { ...blank, correct_answer: e.target.value } : blank) })}><option value="">Выбери вариант</option>{[...new Set(b.choices.map(c => c.trim()).filter(Boolean))].map(choice => <option key={choice}>{choice}</option>)}</select> : <input id={`${id}-blank-${bi}`} maxLength={20000} value={b.correct_answer} onChange={e => update({ ...q, blanks: q.blanks.map((blank, j) => j === bi ? { ...blank, correct_answer: e.target.value } : blank) })} />}<div className="editor-tools"><button type="button" disabled={bi === 0} aria-label={`Поднять поле ${bi + 1}`} onClick={() => update({ ...q, blanks: move(q.blanks, bi, bi - 1) })}>↑</button><button type="button" disabled={bi === q.blanks.length - 1} aria-label={`Опустить поле ${bi + 1}`} onClick={() => update({ ...q, blanks: move(q.blanks, bi, bi + 1) })}>↓</button><button type="button" disabled={q.blanks.length === 1} onClick={() => update({ ...q, blanks: q.blanks.filter((_, j) => j !== bi) })}>Удалить поле</button></div></div>)}<button type="button" className="secondary-action" disabled={q.blanks.length >= 100} onClick={() => update({ ...q, blanks: [...q.blanks, { prompt: '', correct_answer: '', choices: [] }] })}>+ Добавить поле</button></fieldset>}
    <label htmlFor={`${id}-explanation`}>Пояснение к ответу <span className="optional">необязательно</span></label><textarea id={`${id}-explanation`} rows={2} maxLength={20000} value={q.explanation} onChange={e => update({ ...q, explanation: e.target.value })} />
  </section>
}
